name: CI - Build and Push Docker Image

on:
  push:
    branches:
      # Replace with your desired branch
      - develop
    # Trigers only by changes in those files/directories
    paths:
      - dockerfile
      - playbook.yaml
      - pom.xml
      - .github/workflows/docker-cd.yml
      - .github/workflows/docker-ci-pr.yml

env:
  IMAGE_NAME: joska99/java-maven
  ASIGNEES_PR_TO: Joska99
  LABEL_PR: enhancement
  PR_FROM: develop
  PR_TO: master

jobs:
  build-push:
    runs-on: ubuntu-latest

    name: Build Push, increment .env
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          persist-credentials: false
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Create local changes, increment version
        run: |
          echo "tag_version: ${{ steps.version.outputs.version }}" > .env

      #* Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PSWD }}

      #* Push to DockerHub commit Hash
      - name: Build and push Docker image tag from build number
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      #* Push to DockerHub Last Tag + Patch ( + 0.0.1)
      - name: Build and push Docker image tag from last tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"

      #* Push to DockerHub Latest
      - name: Build and push Docker image tag LATEST
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      #* Push updatet repo to master
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: "develop"
          message: "Versioning automatic push"
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}

  PR:
    needs: build-push
    runs-on: ubuntu-latest
    name: PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          persist-credentials: false
          fetch-depth: 0

      - name: create pull request
        run: gh pr create -B master -H develop --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  #     # * Open "PULL REQUEST" from "dev" to "master"
  #     - name: Create Pull Request!
  #       uses: peter-evans/create-pull-request@v5.0.2
  #       with:
  #         branch: create-pr
  #         base: master
  #         title: "New Docker Image Tested and Pushed"
  #         commit-message: "CI passed succsessfuly"
  #         labels: |
  #           ${{ env.LABEL_PR }}
  #         assignees: ${{ env.ASIGNEES_PR_TO }}
  #         token: ${{ secrets.MY_GITHUB_TOKEN }}
  #         delete-branch: true
